# permissions for end users to edit inferenceservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ai-terminal
    app.kubernetes.io/managed-by: kustomize
  name: inferenceservice-editor-role
rules:
- apiGroups:
  - ai.wecoding.top.top.wecoding
  resources:
  - inferenceservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ai.wecoding.top.top.wecoding
  resources:
  - inferenceservices/status
  verbs:
  - get
